Fix laxy computation of diversity based on result_set
error: This code was raising an error on replace! saying `no method
matching writeblock!(::DiskArrays.BroadcastDiskArray{…}`
cause: This was caused because it was calling replace! on a lazy YAXArray. The
replace was trying to write results on the files, but there was no
method defined to make this operation.
solution: define a function instead of calling replace!. This allows to
keep the computation lazy and avoid trying to modify raw data.